### PR TITLE
Schema and ERD

### PR DESCRIPTION
**Pull request by harish08102004**
**New**
- Created Schema and ERD 
- Loom video link for Schema and ERD - https://www.loom.com/share/6e2a8ae9e9d34a9fa9245b4ceffb34c2?sid=6393c16b-3734-438f-abe9-444588fcd71c

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
There should be Admin entity, that manages Destination and Accommodation.
Name and location in Destination Entity? Both specifies the name of the location. Should have proper attributes for destination.
In first proposal, It was explained by you about Accommodation nearby Destination, connection with foreign key, which are missing in this diagram and explanation.
And for Accomodation, rooms availability, and status of those should be maintained separately even as separate entity, which was explained by you in proposal.

**Comment by PRASANNAPATHI** [comment]
Please book a slot in my calendar. Lets have a viva session.

**Comment by harish08102004** [comment]
> There should be Admin entity, that manages Destination and Accommodation. Name and location in Destination Entity? Both specifies the name of the location. Should have proper attributes for destination. In first proposal, It was explained by you about Accommodation nearby Destination, connection with foreign key, which are missing in this diagram and explanation. And for Accomodation, rooms availability, and status of those should be maintained separately even as separate entity, which was explained by you in proposal.

The plan has slightly changed . So there will be no such thing like nearby acommodation , it only shows the acommodations.

I had made some commits.

**Comment by PRASANNAPATHI** [comment]
Approved in viva.

Please, merge it now for Schema & ERD.

**Review by PRASANNAPATHI — APPROVED** [review]

**Pull request merged**
